### ISSUE TITLE
how to install on raspberry pi

### ISSUE THREAD

**Issue by bachoo786** [JiriSko/amixer-webui#13]
Hi I am a total noob.

Just wondering I tried to install amixer-webui on my raspberrypi zero  w and I am using phat dac by pimroni. I am using alsa as well.

I cloned the whole directory to my pi and ran install command. I believe amixer-webui has been installed and I tried to configure the conf file in which I wrote my address of the pi running amixer-webui and the port. 

But I cannot connect to it at all I am on Chrome and I have also tried the android app. None of them work all I get is a spin and after a while a blank white page.

Can someone please help me?

Thanks.

**Comment by bachoo786** [comment]
so I am trying to check if amixer-webui is running and I get the following:

```
pi@raspberrypi:~ $ systemctl status amixer-webui.service
● amixer-webui.service
   Loaded: loaded (/etc/init.d/amixer-webui; generated; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2018-09-28 14:49:22 BST; 11s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 783 ExecStart=/etc/init.d/amixer-webui start (code=exited, status=127)

Sep 28 14:49:22 raspberrypi systemd[1]: Starting amixer-webui.service...
Sep 28 14:49:22 raspberrypi amixer-webui[783]: /bin/sh: 0: Can't open /etc/rc.common
Sep 28 14:49:22 raspberrypi systemd[1]: amixer-webui.service: Control process exited, code=exited status=127
Sep 28 14:49:22 raspberrypi systemd[1]: Failed to start amixer-webui.service.
Sep 28 14:49:22 raspberrypi systemd[1]: amixer-webui.service: Unit entered failed state.
Sep 28 14:49:22 raspberrypi systemd[1]: amixer-webui.service: Failed with result 'exit-code'.


```

Please help me? Also I think the instructions on how to install can be bettered.

**Comment by bachoo786** [comment]
ok when I try to run using this command: `sudo python /usr/share/amixer-webui/alsamixer_webui.py`

I get errors which are here:

```
pi@raspberrypi:~ $ sudo python /usr/share/amixer-webui/alsamixer_webui.py
 * Running on http://192.168.0.38:72/ (Press CTRL+C to quit)
195.75.90.190 - - [28/Sep/2018 14:55:04] "GET / HTTP/1.1" 200 -
195.75.90.190 - - [28/Sep/2018 14:55:04] "GET /css/material.teal-cyan.min.css HTTP/1.1" 200 -
195.75.90.190 - - [28/Sep/2018 14:55:04] "GET /css/material-icons.css HTTP/1.1" 200 -
195.75.90.190 - - [28/Sep/2018 14:55:04] "GET /css/dialog-polyfill.css HTTP/1.1" 200 -
195.75.90.190 - - [28/Sep/2018 14:55:04] "GET /js/material.min.js HTTP/1.1" 200 -
195.75.90.190 - - [28/Sep/2018 14:55:04] "GET /css/style.css HTTP/1.1" 200 -
195.75.90.190 - - [28/Sep/2018 14:55:04] "GET /js/script.js HTTP/1.1" 200 -
195.75.90.190 - - [28/Sep/2018 14:55:04] "GET /js/dialog-polyfill.js HTTP/1.1" 200 -
195.75.90.190 - - [28/Sep/2018 14:55:05] "GET /js/i18n/en-GB.js HTTP/1.1" 404 -
195.75.90.190 - - [28/Sep/2018 14:55:05] "GET /js/i18n/en.js HTTP/1.1" 200 -
ALSA lib control.c:1373:(snd_ctl_open_noupdate) Invalid CTL pulse
amixer: Control device pulse open error: No such file or directory
195.75.90.190 - - [28/Sep/2018 14:55:05] "GET /cards/ HTTP/1.1" 200 -
[2018-09-28 14:55:05,567] ERROR in app: Exception on /controls/ [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/amixer-webui/alsamixer_webui.py", line 235, in get_controls
    data = json.dumps(app.__get_controls__())
  File "/usr/share/amixer-webui/alsamixer_webui.py", line 145, in __get_controls__
    channel_desc = self.__get_channel_name__(amixer_chandesc, interface["name"], i)
  File "/usr/share/amixer-webui/alsamixer_webui.py", line 61, in __get_channel_name__
    if name.split(" ")[-2] in line:
IndexError: list index out of range
195.75.90.190 - - [28/Sep/2018 14:55:05] "GET /controls/?1538142906018 HTTP/1.1" 500 -
195.75.90.190 - - [28/Sep/2018 14:55:05] "GET /hostname/ HTTP/1.1" 200 -
195.75.90.190 - - [28/Sep/2018 14:55:05] "GET /icons/favicon-32x32.png HTTP/1.1" 200 -
ALSA lib control.c:1373:(snd_ctl_open_noupdate) Invalid CTL equal
amixer: Mixer attach equal error: No such file or directory
ALSA lib control.c:1373:(snd_ctl_open_noupdate) Invalid CTL equal
amixer: Control equal open error: No such file or directory
195.75.90.190 - - [28/Sep/2018 14:55:05] "GET /equalizer/ HTTP/1.1" 200 -
195.75.90.190 - - [28/Sep/2018 14:55:11] "GET /icons/favicon-16x16.png HTTP/1.1" 200 -
195.75.90.190 - - [28/Sep/2018 14:55:11] "GET /icons/favicon-96x96.png HTTP/1.1" 200 -
195.75.90.190 - - [28/Sep/2018 14:55:11] "GET /icons/android-chrome-192x192.png HTTP/1.1" 200 -
195.75.90.190 - - [28/Sep/2018 14:55:11] "GET /icons/favicon-194x194.png HTTP/1.1" 200 -
195.75.90.190 - - [28/Sep/2018 14:55:11] "GET /icons/favicon.ico HTTP/1.1" 200 -

```

**Comment by alekksander** [comment]
did You actually started the service? see output of „/etc/init.d/amixer-webui status”. if it doesn't run „/etc/init.d/amixer-webui start” and check status again. also in android app make sure You have given it the right ip address.

**Comment by therion23** [comment]
I have the exact same combination as you do, here was my solution:
sudo apt-get install python-flask

**Comment by bachoo786** [comment]
ok so after cloning the directory what shall i do next?

**Comment by bachoo786** [comment]
ok I think I resolved it I had to run `make install` command. 

quick question will the service run automatically when I reboot the raspberry?

**Comment by therion23** [comment]
Not if you use systemd - have a look at issue #16 . Works fine with SysV init though.
